name: Docker Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release (e.g., v1.9.0)"
        required: true

permissions:
  contents: read

jobs:
  docker-release:
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      RELEASE: ${{ github.event.inputs.release || github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Build Docker Images
        run: make VERSION=${RELEASE:1} DOCKER=coredns -f Makefile.docker release
      - name: Show Docker Images
        run: docker images
      - name: Docker login
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1  # v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish Docker Images
        run: make VERSION=${RELEASE:1} DOCKER=coredns -f Makefile.docker docker-push
