name: Go Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.0'
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          ( cd request; go test -race ./... )
          ( cd core; go test -race  ./... )
          ( cd coremain; go test -race ./... )

  test-plugins:
    name: Test Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.0'
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: ( cd plugin; go test -race ./... )

  test-e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.0'
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go install github.com/fatih/faillint@latest
          ( cd test; go test -race ./... )

  test-makefile-release:
    name: Test Makefile.release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install make curl

      - name: Test Makefile.release
        run: make GITHUB_ACCESS_TOKEN=x -n release github-push -f Makefile.release

      - name: Test Makefile.docker
        run: make VERSION=x DOCKER=x -n release docker-push -f Makefile.docker
