name: Make Doc

on:
  schedule:
    - cron: '22 10 * * 0'

permissions: read-all

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Setup Go Version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Update Docs
        run: |
          bash -x -e ./.github/fixup_file_mtime.sh
          make -f Makefile.doc

      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "coredns[bot]"
          git config user.email "bot@bot.coredns.io"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -s -m 'auto make -f Makefile.doc'
            git push
          fi
